[package]
name = "rsvz-pvz-emulator-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PvZ-Emulator backend adapter for RustVsZombies"

[features]
default = []
host = [
    "dep:rsvz-profiling",
    "dep:serde",
    "dep:serde_json",
]

[dependencies]
pe-rs = { workspace = true }
rsvz-backend-api = { workspace = true }
rsvz-model = { workspace = true }
rsvz-profiling = { workspace = true, optional = true }
thiserror = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[lints]
workspace = true
