//! Build and inject a PvZ 1.0.0.1051 script runner.

use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result, bail};
use clap::Args;

use crate as tooling;
use crate::{BuildProfile, ScriptRunnerOptions};

const DEFAULT_TARGET: &str = tooling::DEFAULT_TARGET;
const DEV_SCRIPTS_DIR: &str = "dev-scripts";
static RUN_SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// Build and inject a PvZ 1.0.0.1051 script runner or an opaque DLL.
#[derive(Args, Debug, Clone)]
pub struct Inject1051Args {
    /// Standalone Rust script source prepared by the rsvz CLI.
    #[arg(
        value_name = "SCRIPT",
        conflicts_with_all = ["dll", "script_crate", "dev_script"],
        required_unless_present_any = ["dll", "script_crate", "dev_script"]
    )]
    script: Option<PathBuf>,
    /// Build debug artifacts instead of release artifacts.
    #[arg(long)]
    debug: bool,
    /// RustVsZombies workspace root. Defaults to searching from the current directory, then the CLI executable path.
    #[arg(long, value_name = "PATH")]
    workspace_root: Option<PathBuf>,
    /// Complete opaque DLL to inject instead of building a script runner.
    #[arg(long, conflicts_with_all = ["script", "script_crate", "dev_script"])]
    dll: Option<PathBuf>,
    /// Target PvZ process id. Required when multiple supported windows exist.
    #[arg(long)]
    pid: Option<u32>,
    /// Build artifacts and print paths without launching the injector.
    #[arg(long)]
    build_only: bool,
    /// External script crate directory or Cargo.toml to link into a generated runner DLL.
    #[arg(long, value_name = "PATH", conflicts_with = "dev_script")]
    script_crate: Option<PathBuf>,
    /// Worktree-local script under dev-scripts, or an absolute script crate path.
    #[arg(long, value_name = "PATH", conflicts_with = "script_crate")]
    dev_script: Option<PathBuf>,
    /// Script name exposed by the generated runner DLL.
    #[arg(long)]
    script_name: Option<String>,
    /// Package name when the script crate path belongs to a multi-package workspace.
    #[arg(long)]
    script_package: Option<String>,
    /// Feature to enable on the user script package. May be repeated.
    #[arg(long = "script-feature")]
    script_features: Vec<String>,
    /// Disable the user script package's default features.
    #[arg(long)]
    no_script_default_features: bool,
    /// Host control-result path. Defaults to a temp path generated by the CLI.
    #[arg(long)]
    report: Option<PathBuf>,
    /// Optional root JSON artifact published by the script.
    #[arg(long)]
    output: Option<PathBuf>,
    /// Maximum time to wait for the control result. The injected script keeps running after timeout.
    #[arg(long = "wait-timeout-secs")]
    wait_timeout_secs: Option<u64>,
    /// Do not wait for a script completion report after injection.
    #[arg(long)]
    no_wait: bool,
    /// Build the injected runtime with low-overhead battle fast-forward profiling enabled.
    #[arg(long)]
    fast_forward_profiler: bool,
}

impl Inject1051Args {
    pub fn take_bare_script(&mut self) -> Option<(PathBuf, Option<String>)> {
        self.script.take().map(|script| (script, self.script_name.clone()))
    }

    #[must_use]
    pub fn workspace_root(&self) -> Option<&Path> {
        self.workspace_root.as_deref()
    }

    pub fn use_prepared_script(&mut self, manifest: PathBuf, default_name: String) -> Result<()> {
        if self.script_package.is_some() || !self.script_features.is_empty() || self.no_script_default_features {
            bail!("bare .rs scripts cannot use package or script-feature selection options");
        }
        self.script_crate = Some(manifest);
        self.script_name.get_or_insert(default_name);
        Ok(())
    }
}

/// Build, run and clean up a disposable, profile-isolated 1051 process.
#[derive(Args, Debug, Clone)]
pub struct Run1051Args {
    #[command(flatten)]
    pub script: Inject1051Args,
    #[arg(long, value_name = "EXE")]
    game: PathBuf,
    /// Directory containing the template's users.dat and user*.dat (copied, never edited).
    #[arg(long, value_name = "USERDATA")]
    profile_template: PathBuf,
    #[arg(long, default_value_t = 60, value_parser = clap::value_parser!(u64).range(1..))]
    timeout_secs: u64,
}

pub fn run_owned(args: Run1051Args, root: &Path, current_dir: &Path) -> Result<()> {
    use crate::live_process::{Sandbox, check_deadline, copy_tree, module_loaded, poll_delay};
    use crate::owned_game::{OwnedGame, ensure_no_game, verify_exe};
    let script = &args.script;
    if script.pid.is_some() || script.no_wait || script.dll.is_some() || script.wait_timeout_secs.is_some() {
        bail!("run-1051 owns its game: --pid, --no-wait, --dll and --wait-timeout-secs are not supported");
    }
    let game_source = fs::canonicalize(absolute_output_path(current_dir, &args.game))?;
    let template = fs::canonicalize(absolute_output_path(current_dir, &args.profile_template))?;
    verify_exe(&game_source)?;
    if !template.join("users.dat").is_file() {
        bail!("profile template must contain users.dat");
    }
    let profile = BuildProfile::from_debug_flag(script.debug);
    let ResolvedInput::Runner { build, config } = resolve_input(root, current_dir, script, profile)? else {
        bail!("run-1051 requires a script");
    };
    let dll = tooling::cargo_build_generated_runner(root, &build)?;
    tooling::cargo_build_injector(root, DEFAULT_TARGET, profile)?;
    let injector = root
        .join("target")
        .join(DEFAULT_TARGET)
        .join(profile.dir_name())
        .join(tooling::INJECTOR_EXE_NAME);
    if script.build_only {
        println!("runner DLL: {}\ninjector EXE: {}", dll.display(), injector.display());
        return Ok(());
    }
    let deadline = Instant::now() + Duration::from_secs(args.timeout_secs);
    ensure_no_game()?;
    let sandbox = Sandbox::new("1051")?;
    let directory = sandbox.0.join("game");
    copy_tree(
        game_source.parent().context("game has no parent directory")?,
        &directory,
        deadline,
    )?;
    let userdata = directory.join("userdata");
    // Both paths are within a newly created, private sandbox.
    if userdata.exists() {
        fs::remove_dir_all(&userdata)?;
    }
    copy_tree(&template, &userdata, deadline)?;
    let executable = directory.join(game_source.file_name().context("game filename missing")?);
    remove_existing_report(&config.control_result_path)?;
    if let Some(output) = &config.output_path {
        remove_existing_report(output)?;
    }
    let json = serde_json::to_string(&config)?;
    let game = OwnedGame::launch(&executable, &directory)?;
    let module = format!("rsvz_backend_1051_inject_{}.dll", game.pid());
    let unload_args = vec!["--unload".into(), "--pid".into(), game.pid().to_string().into()];
    let result = (|| {
        game.wait_ready(deadline)?;
        run_owned_injector(
            &injector,
            &tooling::injector_command_args(&dll, Some(game.pid()), Some(&json)),
            &sandbox.0,
            &game,
            deadline,
        )?;
        loop {
            game.alive()?;
            check_deadline(deadline)?;
            if config.control_result_path.is_file() {
                break;
            }
            poll_delay();
        }
        let terminal = wait_for_report(&config.control_result_path, Duration::ZERO, &config.run_id)?;
        run_owned_injector(&injector, &unload_args, &sandbox.0, &game, deadline)?;
        if module_loaded(game.pid(), std::ffi::OsStr::new(&module))? {
            bail!("1051 DLL remained loaded after unload");
        }
        game.observe_alive(deadline)?;
        eprintln!("1051 DLL absent; game alive after unload");
        match terminal {
            tooling::wire::Terminal::Success {} => Ok(()),
            tooling::wire::Terminal::Failure { message } => bail!("script failed: {message}"),
        }
    })();
    if result.is_err() && game.alive().is_ok() {
        // A separate, bounded cleanup window; an in-flight injector is reaped inside its runner.
        if let Err(error) = run_owned_injector(
            &injector,
            &unload_args,
            &sandbox.0,
            &game,
            Instant::now() + Duration::from_secs(6),
        ) {
            eprintln!("1051 graceful cleanup failed; owned-process termination fallback: {error:#}");
        }
    }
    game.terminate()?;
    eprintln!("owned 1051 process reaped: {}", game.pid());
    result
}

fn run_owned_injector(
    executable: &Path, arguments: &[std::ffi::OsString], root: &Path, game: &crate::owned_game::OwnedGame,
    deadline: Instant,
) -> Result<()> {
    let mut child = crate::live_process::ChildGuard {
        child: Command::new(executable).args(arguments).current_dir(root).spawn()?,
        terminate_on_drop: true,
    };
    let result = (|| {
        loop {
            if let Some(status) = child.try_wait()? {
                if !status.success() {
                    bail!("injector failed: {status}");
                }
                return Ok(());
            }
            game.alive()?;
            crate::live_process::check_deadline(deadline)?;
            crate::live_process::poll_delay();
        }
    })();
    if result.is_err() {
        // The remote thread may still read its allocation. Kill/reap the owned game FIRST,
        // then the injector; never drop a remote allocation under a running target thread.
        game.terminate()?;
        child.terminate()?;
    }
    result
}

pub fn run(args: Inject1051Args, root: &Path, current_dir: &Path) -> Result<()> {
    let profile = BuildProfile::from_debug_flag(args.debug);
    let injector_exe = root
        .join("target")
        .join(DEFAULT_TARGET)
        .join(profile.dir_name())
        .join(tooling::INJECTOR_EXE_NAME);
    let input = resolve_input(root, current_dir, &args, profile)?;

    let injected_dll = match &input {
        ResolvedInput::Runner { build, .. } => tooling::cargo_build_generated_runner(root, build)?,
        ResolvedInput::OpaqueDll(dll) => dll.clone(),
    };
    tooling::cargo_build_injector(root, DEFAULT_TARGET, profile)?;

    ensure_file(&injected_dll, "injected DLL")?;
    ensure_file(&injector_exe, "injector.exe")?;

    if args.build_only {
        match input {
            ResolvedInput::Runner { .. } => println!("runner DLL: {}", injected_dll.display()),
            ResolvedInput::OpaqueDll(_) => println!("DLL: {}", injected_dll.display()),
        }
        println!("injector EXE: {}", injector_exe.display());
        return Ok(());
    }

    let run_config_json = match &input {
        ResolvedInput::Runner { config, .. } => {
            Some(serde_json::to_string(config).context("序列化 1051 runner config JSON 失败")?)
        }
        ResolvedInput::OpaqueDll(_) => None,
    };
    let injector_args = tooling::injector_command_args(&injected_dll, args.pid, run_config_json.as_deref());
    if let ResolvedInput::Runner { config, .. } = &input {
        remove_existing_report(&config.control_result_path)?;
        if let Some(output) = config.output_path.as_deref() {
            remove_existing_report(output)?;
        }
    }
    let status = Command::new(&injector_exe)
        .args(&injector_args)
        .current_dir(root)
        .status()
        .with_context(|| format!("启动 injector 失败: {}", injector_exe.display()))?;

    if !status.success() {
        bail!("injector 运行失败，exit code: {:?}", status.code());
    }

    if let ResolvedInput::Runner { config, .. } = &input {
        if args.no_wait {
            println!("control result: {}", config.control_result_path.display());
            if let Some(output) = config.output_path.as_deref() {
                println!("artifact output: {}", output.display());
            }
        } else {
            match wait_for_report(
                &config.control_result_path,
                normal_script_timeout(args.wait_timeout_secs),
                &config.run_id,
            )? {
                tooling::wire::Terminal::Success {} => println!("script completed"),
                tooling::wire::Terminal::Failure { message } => {
                    bail!("script failed: {message}");
                }
            }
        }
    }

    Ok(())
}

fn build_run_config(
    current_dir: &Path, script_result_path: PathBuf, output_path: Option<PathBuf>,
) -> Result<tooling::wire::RunConfig> {
    let run_id = new_run_id();
    let config = tooling::wire::RunConfig {
        schema_version: tooling::wire::SCHEMA_VERSION,
        run_id: run_id.clone(),
        output_path: output_path
            .as_deref()
            .map(|path| absolute_output_path(current_dir, path)),
        control_result_path: absolute_output_path(current_dir, &script_result_path),
    };
    config
        .validate(Some(&run_id))
        .map_err(anyhow::Error::msg)
        .context("校验 1051 runner config 失败")?;
    Ok(config)
}

fn new_run_id() -> String {
    let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
    let sequence = RUN_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    format!("{:x}-{:x}-{sequence:x}", std::process::id(), now.as_nanos())
}

fn absolute_output_path(current_dir: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        current_dir.join(path)
    }
}

fn normal_script_timeout(timeout_secs: Option<u64>) -> Duration {
    Duration::from_secs(timeout_secs.unwrap_or(60))
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct ScriptSource {
    script_crate: PathBuf,
    script_name: String,
}

enum ResolvedInput {
    Runner {
        build: tooling::ScriptRunnerBuild,
        config: tooling::wire::RunConfig,
    },
    OpaqueDll(PathBuf),
}

fn resolve_input(
    root: &Path, current_dir: &Path, args: &Inject1051Args, profile: BuildProfile,
) -> Result<ResolvedInput> {
    let Some(source) = resolve_script_source(root, args)? else {
        let dll = args
            .dll
            .as_deref()
            .context("clap requires a script source or an opaque DLL")?;
        let dll = fs::canonicalize(absolute_output_path(current_dir, dll))
            .with_context(|| format!("规范化外部 DLL 路径失败: {}", dll.display()))?;
        return Ok(ResolvedInput::OpaqueDll(dll));
    };

    let build = tooling::prepare_script_runner(
        root,
        ScriptRunnerOptions {
            current_dir,
            script_crate: &source.script_crate,
            script_name: &source.script_name,
            script_package: args.script_package.as_deref(),
            script_features: &args.script_features,
            script_default_features: !args.no_script_default_features,
            target: DEFAULT_TARGET,
            profile,
            fast_forward_profiler: args.fast_forward_profiler,
        },
    )?;
    let report = args
        .report
        .clone()
        .unwrap_or_else(|| default_report_path(&build.script_name));
    if let Some(output) = args.output.as_deref()
        && report_paths_conflict(current_dir, &report, output)
    {
        bail!("1051 control result and artifact output paths must be different");
    }
    let config = build_run_config(current_dir, report, args.output.clone())?;
    Ok(ResolvedInput::Runner { build, config })
}

fn resolve_script_source(root: &Path, args: &Inject1051Args) -> Result<Option<ScriptSource>> {
    if args.script.is_some() {
        bail!("bare .rs scripts must be prepared by the rsvz CLI");
    }
    if let Some(script_crate) = args.script_crate.as_deref() {
        let script_name = args
            .script_name
            .as_deref()
            .context("--script-name is required when --script-crate is used")?;
        return Ok(Some(ScriptSource {
            script_crate: script_crate.to_path_buf(),
            script_name: script_name.to_owned(),
        }));
    }

    if let Some(dev_script) = args.dev_script.as_deref() {
        let script_crate = if dev_script.is_absolute() {
            dev_script.to_path_buf()
        } else {
            root.join(DEV_SCRIPTS_DIR).join(dev_script)
        };
        let script_name = match args.script_name.as_deref() {
            Some(script_name) => script_name.to_owned(),
            None => dev_script_name(dev_script)?,
        };
        return Ok(Some(ScriptSource {
            script_crate,
            script_name,
        }));
    }

    if args.script_name.is_some() {
        bail!("--script-name requires --script-crate or --dev-script");
    }
    if args.script_package.is_some() {
        bail!("--script-package requires --script-crate or --dev-script");
    }
    if !args.script_features.is_empty() || args.no_script_default_features {
        bail!("script feature options require --script-crate or --dev-script");
    }
    if args.report.is_some() || args.output.is_some() || args.wait_timeout_secs.is_some() || args.no_wait {
        bail!("runner/report options require --script-crate or --dev-script");
    }
    if args.dll.is_some() && args.fast_forward_profiler {
        bail!("--fast-forward-profiler cannot modify an opaque external --dll");
    }

    Ok(None)
}

fn dev_script_name(path: &Path) -> Result<String> {
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .with_context(|| format!("无法从 --dev-script 推断 script name: {}", path.display()))?;
    Ok(name.to_owned())
}

fn ensure_file(path: &Path, label: &str) -> Result<()> {
    let metadata = fs::metadata(path).with_context(|| format!("{label} 不存在或无法读取: {}", path.display()))?;
    if !metadata.is_file() {
        bail!("{label} 不是文件: {}", path.display());
    }
    Ok(())
}

fn remove_existing_report(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("删除旧 report 失败: {}", path.display())),
    }
}

fn report_paths_conflict(current_dir: &Path, left: &Path, right: &Path) -> bool {
    comparable_report_path(current_dir, left) == comparable_report_path(current_dir, right)
}

fn comparable_report_path(current_dir: &Path, path: &Path) -> String {
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        current_dir.join(path)
    };
    let path = lexical_normalize_path(&path);
    let text = path.to_string_lossy().replace('\\', "/");
    if cfg!(windows) { text.to_ascii_lowercase() } else { text }
}

fn lexical_normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    let mut normal_components = 0usize;
    for component in path.components() {
        match component {
            Component::Prefix(_) | Component::RootDir => normalized.push(component.as_os_str()),
            Component::CurDir => {}
            Component::Normal(part) => {
                normalized.push(part);
                normal_components = normal_components.saturating_add(1);
            }
            Component::ParentDir => {
                if normal_components > 0 {
                    let _ = normalized.pop();
                    normal_components -= 1;
                } else if !path.has_root() {
                    normalized.push("..");
                }
            }
        }
    }
    normalized
}

fn default_report_path(script: &str) -> PathBuf {
    let safe_name = safe_script_name(script);
    std::env::temp_dir().join(format!("rsvz-1051-{safe_name}-{}.report", std::process::id()))
}

fn safe_script_name(script: &str) -> String {
    script
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>()
}

fn wait_for_report(path: &Path, timeout: Duration, expected_run_id: &str) -> Result<tooling::wire::Terminal> {
    let started = Instant::now();
    loop {
        if let Some(text) = read_published_result(path, "script")? {
            return parse_script_result(&text, expected_run_id);
        }
        if started.elapsed() >= timeout {
            bail!("等待 script result 超时: {}", path.display());
        }
        thread::sleep(Duration::from_millis(200));
    }
}

fn read_published_result(path: &Path, kind: &str) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error).with_context(|| format!("读取 {kind} result 失败: {}", path.display())),
    }
}

fn parse_script_result(text: &str, expected_run_id: &str) -> Result<tooling::wire::Terminal> {
    let result: tooling::wire::RunResult = serde_json::from_str(text).context("解析 1051 script result JSON 失败")?;
    result
        .validate(Some(expected_run_id))
        .map_err(anyhow::Error::msg)
        .context("校验 1051 script result 失败")?;
    Ok(result.terminal)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_config_contains_only_host_environment_data() {
        let config = build_run_config(
            Path::new("C:/work"),
            PathBuf::from("control.json"),
            Some(PathBuf::from("artifact.json")),
        )
        .expect("config");
        let value = serde_json::to_value(config).expect("serialize");
        for forbidden in [
            "bench",
            "measure",
            "trials",
            "duration",
            "finish_policy",
            "entry_scene",
            "auto_enter",
        ] {
            assert!(value.get(forbidden).is_none(), "wire retained {forbidden}");
        }
        assert!(
            value["output_path"]
                .as_str()
                .unwrap()
                .replace('\\', "/")
                .ends_with("/artifact.json")
        );
        assert!(
            value["control_result_path"]
                .as_str()
                .unwrap()
                .replace('\\', "/")
                .ends_with("/control.json")
        );
    }

    #[test]
    fn report_paths_are_compared_after_lexical_normalization() {
        let current = Path::new("C:/work");
        assert!(report_paths_conflict(
            current,
            Path::new("out/../result.json"),
            Path::new("result.json")
        ));
        assert!(!report_paths_conflict(
            current,
            Path::new("control.json"),
            Path::new("artifact.json")
        ));
    }

    #[test]
    fn control_result_validation_rejects_stale_runs() {
        let result = tooling::wire::RunResult {
            schema_version: tooling::wire::SCHEMA_VERSION,
            run_id: "run-1".to_owned(),
            terminal: tooling::wire::Terminal::Success {},
        };
        let text = serde_json::to_string(&result).expect("serialize");
        assert_eq!(
            parse_script_result(&text, "run-1").expect("valid result"),
            tooling::wire::Terminal::Success {}
        );
        assert!(parse_script_result(&text, "stale").is_err());
    }
}
