[package]
name = "mge_qunzeng"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
rsvz = { path = "../../../crates/scripting/api" }

[workspace]
resolver = "3"

[dev-dependencies]
rsvz = { path = "../../../crates/scripting/api", features = ["pvz-emulator"] }
rsvz-pvz-emulator-backend = { path = "../../../crates/backends/pvz_emulator/backend" }
